services:
  - type: web
    name: dark-store-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PAYU_KEY
        sync: false
      - key: PAYU_SALT
        sync: false
      - key: PAYU_VERIFY_URL
        value: https://info.payu.in/merchant/postservice.php?form=2
      - key: PUBLIC_BASE_URL
        sync: false
      - key: WEBHOOK_HOST
        value: 0.0.0.0
      - key: WEBHOOK_PORT
        value: 10000
